# Generated by Django 5.0.6 on 2024-05-31 15:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("imdb_rating", models.FloatField()),
                ("title", models.CharField(max_length=100)),
                ("year", models.CharField(max_length=10)),
                ("imdb_id", models.CharField(max_length=20, unique=True)),
                (
                    "poster_url",
                    models.URLField(default="https://example.com/default_poster.jpg"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_public", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.users"
                    ),
                ),
                ("movies", models.ManyToManyField(to="movies.movie")),
            ],
        ),
    ]
