# Generated by Django 5.0.6 on 2024-06-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="movies",
            field=models.ManyToManyField(blank=True, to="movies.movie"),
        ),
    ]
